# http://travis-ci.org/#!/graphite-project/ceres
language: python
python:
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - "pypy"
install:
    - pip install -r test_requirements.txt
    - python setup.py install
script:
    - nosetests
#XXX Once flake8 updates its deps to pep8 > 1.6.0, E111 changes number to E114
    - flake8 --max-line-length=100 --ignore=E111,E121 ceres.py tests/*.py bin/*

sudo: false
